package MedicalStore;


/**
* MedicalStore/medintf.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from store.idl
* Wednesday, 11 April, 2018 9:52:50 PM IST
*/

public interface medintf extends medintfOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface medintf
