package MedicalStore;


/**
* MedicalStore/medintfOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from store.idl
* Wednesday, 11 April, 2018 9:52:50 PM IST
*/

public interface medintfOperations 
{
  String check_medicine (String med_id);
  String process_medicine (String med_id, int quantity);
  int total_price ();
  String pay_bill ();
} // interface medintfOperations
