package MedicalStore;

/**
* MedicalStore/MedicinesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from store.idl
* Saturday, 14 April, 2018 10:58:32 AM IST
*/

public final class MedicinesHolder implements org.omg.CORBA.portable.Streamable
{
  public MedicalStore.Medicines value = null;

  public MedicinesHolder ()
  {
  }

  public MedicinesHolder (MedicalStore.Medicines initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MedicalStore.MedicinesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MedicalStore.MedicinesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MedicalStore.MedicinesHelper.type ();
  }

}
